version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: imobia_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imobia
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - desafio_net

volumes:
  postgres_data:

networks:
  desafio_net:
